/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_checker_3 (
    input clk,
    input rst,
    input a,
    input b,
    input cin,
    input sum,
    input carry,
    output reg out
  );
  
  
  
  reg [1:0] M_adder_d, M_adder_q = 1'h0;
  
  always @* begin
    M_adder_d = M_adder_q;
    
    M_adder_d = a + b + cin;
    if (M_adder_q[0+0-:1] != sum || M_adder_q[1+0-:1] != carry) begin
      out = 1'h1;
    end else begin
      out = 1'h0;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_adder_q <= 1'h0;
    end else begin
      M_adder_q <= M_adder_d;
    end
  end
  
endmodule
